### PR TITLE
Show costume

### PR DESCRIPTION
**Pull request by leetenc**
Added Costume's Show Path, Edit, Delete.
Also updated the devise user to allow profile pic selection and navigation to show the profile pic as avatar

### CODE REVIEW

**Comment by leetenc** [comment]
@TalinaBay I think  we have an issue here with Show Costume.  @hanna-koskela @kjam0.   Talina and I both created costume/show.html.erb each for two different reasons. My being edit and delete costume, Talina is to rent teh costume. We need to discuss how we might have to merge  or I go straight to edit from costume#index which is not ideal.  

image

**Comment by hanna-koskela** [comment]
@leetenc Maybe we could route to "your" show page via "My Costumes" only? And give it a route eg. "my_costume".

**Comment by leetenc** [comment]
I thought about it, I think we could still use the same show page but I'll hide the edit and delete button when the user does not own the costume. Don't forget we also allow the owner to block the costume for a period of time by booking it. So I'll merge the features of Talina's and my into one - hope that works 

> @leetenc Maybe we could route to "your" show page via "My Costumes" only? And give it a route eg. "my_costume".

**Comment by leetenc** [comment]
image

**Comment by hanna-koskela** [comment]
@leetenc Did you merge this already? Who reviewed it?

**Pull request merged**
