### PR TITLE
costume controller bug and temporary booking show

### PR DESCRIPTION
**Pull request by leetenc**
After I've merged Talina's show.html.erb with mine, I found a bug in the Costume.rb controller where if you can only click on your own costume but no one else's to show.

Since we are demoing on Saturday, I thought I'd give it an overall test.  But I found that  booking index html is blank which would be crucial - I understand Hanna is working on it, so I created a temporary index page (copied from costume index page) so I can see my bookings. So the currently it is a bare bone working version that can be  demoed on Saturday.  I'm sure we will be able to do some more between now and then.

-  I also was testing the calendar date range selection.  Unfortunately to do that I need to create the My Bookings feature which includes :
1. Bookings Controller index method and the Bookings Controller create method.  this is simple codes based on templates
2. I had to create a Bookings index page to show the list of bookings belonging to the login user - this is just copy paste from index of costume.  As mention above, this is temporary only for my testing. I understand Hanna is working on this. - perhaps when it's ready we can override my version, or merge.

### CODE REVIEW

**Comment by leetenc** [comment]
There is a bug at the moment with date range.  
In the show form:

image

If you put an end date before the start date, it goes to this ugly form for some reason.

image

We will need the TA's help on this one

**Comment by leetenc** [comment]
The second bug with the date range is that it doesn't take into account if your selected date range also covers an unavailable range.  So you can select a date range that contain unavailable dates.  Nothing we can do about it for now unless we do extra complex  logic 
image

**Comment by leetenc** [comment]
Finally, editing a booking (change dates or delete the booking) is not there yet.  not sure if @kjam0 taking on those.

**Comment by hanna-koskela** [comment]
I'm working on the booking related things (edit and delete) @leetenc 😃

**Comment by hanna-koskela** [comment]
Basically all booking related things other than new and create will be in my current branch.

**Pull request merged**
